/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Bean.Item;
import Bean.Stock;
import Bean.StockBatch;
import Logic.SystemMenuBar;
import Manager.MessageManager;
import Manager.StockManager;
import java.awt.event.KeyEvent;
import newException.DatabaseException;
import newException.nullBatchNoException;
import newException.nullCostPriceException;
import newException.nullCreateDateException;
import newException.nullCreateTimeException;
import newException.nullCreateUserException;
import newException.nullExpDateException;
import newException.nullItemNameException;
import newException.nullQuantityException;
import newException.nullResalpriceException;

/**
 *
 * @author Chazool
 */
public class GUIAddStock extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public GUIAddStock() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        txtItemBatchNo = new javax.swing.JTextField();
        butAdd = new javax.swing.JButton();
        butCancel = new javax.swing.JButton();
        txtCostPrice = new javax.swing.JFormattedTextField();
        txtExpDate = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JFormattedTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblMassage = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLayeredPane4 = new javax.swing.JLayeredPane();
        txtItemBarcode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtResalePrice = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLayeredPane2 = new javax.swing.JLayeredPane();
        jLayeredPane3 = new javax.swing.JLayeredPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuUpdateUser = new javax.swing.JMenu();
        MenuUserAdd = new javax.swing.JMenuItem();
        MenuUserUpdate = new javax.swing.JMenuItem();
        MenuUserDelete = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        MenuAdingDrugs = new javax.swing.JMenuItem();
        MenuAddingDrugsItem = new javax.swing.JMenuItem();
        MenuAddingStockDrugs = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MenuUpdateDrugs = new javax.swing.JMenuItem();
        MenuUpdateDrugsItem = new javax.swing.JMenuItem();
        MenuUpdateStockDrugs = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MenuDeleteDrugs = new javax.swing.JMenuItem();
        MenuDeleteItemDrugs = new javax.swing.JMenuItem();
        MenuDeleteStockDrugs = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        MenuLogOut = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pharmacy System");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                jPanel1ComponentResized(evt);
            }
        });

        jLayeredPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Item Name :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Batch No :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Cost Price :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("EXP Date :");

        txtItemName.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtItemName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtItemNameKeyPressed(evt);
            }
        });

        txtItemBatchNo.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        butAdd.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butAdd.setText("Add");
        butAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butAddActionPerformed(evt);
            }
        });

        butCancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        butCancel.setText("Cancel");
        butCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butCancelActionPerformed(evt);
            }
        });

        txtCostPrice.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0.00"))));
        txtCostPrice.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        txtExpDate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("dd-MM-yyyy"))));
        txtExpDate.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtExpDate.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtExpDateKeyTyped(evt);
            }
        });

        jLabel6.setText("100.50");

        jLabel7.setText("30-12-2015");

        txtQuantity.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));
        txtQuantity.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Quantity :");

        jLabel9.setText("12");

        lblMassage.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMassage.setForeground(new java.awt.Color(102, 0, 0));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(204, 204, 204));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Add Stock Item");

        jLayeredPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        txtItemBarcode.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtItemBarcode.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtItemBarcodeKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Barcode :");

        javax.swing.GroupLayout jLayeredPane4Layout = new javax.swing.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane4Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtItemBarcode)
                .addContainerGap())
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredPane4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtItemBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap())
        );
        jLayeredPane4.setLayer(txtItemBarcode, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane4.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        txtResalePrice.setEditable(false);
        txtResalePrice.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtResalePrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtResalePriceKeyPressed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Price :");

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredPane1Layout.createSequentialGroup()
                        .addComponent(lblMassage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(butCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(butAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLayeredPane4)
                    .addGroup(jLayeredPane1Layout.createSequentialGroup()
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtResalePrice)
                            .addComponent(txtExpDate)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtItemName)
                            .addComponent(txtCostPrice)
                            .addComponent(txtQuantity)
                            .addComponent(txtItemBatchNo, javax.swing.GroupLayout.DEFAULT_SIZE, 321, Short.MAX_VALUE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtResalePrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtItemBatchNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCostPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtExpDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(butAdd)
                        .addComponent(butCancel))
                    .addComponent(lblMassage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jLayeredPane1.setLayer(jLabel1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel3, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel5, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtItemName, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtItemBatchNo, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(butAdd, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(butCancel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtCostPrice, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtExpDate, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel6, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel7, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtQuantity, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel8, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel9, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(lblMassage, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel10, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLayeredPane4, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(txtResalePrice, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredPane1.setLayer(jLabel11, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane2Layout = new javax.swing.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jLayeredPane3Layout = new javax.swing.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1036, Short.MAX_VALUE)
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(jLayeredPane1)
                .addGap(261, 261, 261))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLayeredPane2)
                    .addComponent(jLayeredPane3))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredPane2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLayeredPane3)
                .addContainerGap())
        );

        jMenu1.setText("System");

        MenuUpdateUser.setText("User");

        MenuUserAdd.setText("Add User");
        MenuUserAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUserAddActionPerformed(evt);
            }
        });
        MenuUpdateUser.add(MenuUserAdd);

        MenuUserUpdate.setText("Update User");
        MenuUserUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUserUpdateActionPerformed(evt);
            }
        });
        MenuUpdateUser.add(MenuUserUpdate);

        MenuUserDelete.setText("Delete User");
        MenuUserDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUserDeleteActionPerformed(evt);
            }
        });
        MenuUpdateUser.add(MenuUserDelete);

        jMenu1.add(MenuUpdateUser);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenu3.setText("Adding");

        MenuAdingDrugs.setText("Drugs");
        MenuAdingDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAdingDrugsActionPerformed(evt);
            }
        });
        jMenu3.add(MenuAdingDrugs);

        MenuAddingDrugsItem.setText("Drugs Item");
        MenuAddingDrugsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAddingDrugsItemActionPerformed(evt);
            }
        });
        jMenu3.add(MenuAddingDrugsItem);

        MenuAddingStockDrugs.setText("Drugs Stock");
        MenuAddingStockDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAddingStockDrugsActionPerformed(evt);
            }
        });
        jMenu3.add(MenuAddingStockDrugs);

        jMenu2.add(jMenu3);

        jMenu4.setText("Update");

        MenuUpdateDrugs.setText("Drugs");
        MenuUpdateDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUpdateDrugsActionPerformed(evt);
            }
        });
        jMenu4.add(MenuUpdateDrugs);

        MenuUpdateDrugsItem.setText("Drugs Item");
        MenuUpdateDrugsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUpdateDrugsItemActionPerformed(evt);
            }
        });
        jMenu4.add(MenuUpdateDrugsItem);

        MenuUpdateStockDrugs.setText("Drugs Stock");
        MenuUpdateStockDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUpdateStockDrugsActionPerformed(evt);
            }
        });
        jMenu4.add(MenuUpdateStockDrugs);

        jMenu2.add(jMenu4);

        jMenu5.setText("Delete");

        MenuDeleteDrugs.setText("Drugs");
        jMenu5.add(MenuDeleteDrugs);

        MenuDeleteItemDrugs.setText("Drugs Item");
        jMenu5.add(MenuDeleteItemDrugs);

        MenuDeleteStockDrugs.setText("Drugs Stock");
        MenuDeleteStockDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDeleteStockDrugsActionPerformed(evt);
            }
        });
        jMenu5.add(MenuDeleteStockDrugs);

        jMenu2.add(jMenu5);

        jMenuBar1.add(jMenu2);

        jMenu6.setText("Home");
        jMenuBar1.add(jMenu6);

        MenuLogOut.setText("LogOut");
        MenuLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuLogOutMouseClicked(evt);
            }
        });
        MenuLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLogOutActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuLogOut);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Enter Barcord And Get Data
     *
     * @param Key
     */
    private void BarcordEnter(int Key) {
        String Message = "";
        if (Key == KeyEvent.VK_ENTER) {
            try {
                StockManager.Select(txtItemBarcode.getText().trim(), this);
            } catch (NullPointerException ex) {
                Message = "Invalid Barcode";
            }
        }
        lblMassage.setText(Message);
    }

    //System Menu Bar
    SystemMenuBar MenuBar = new SystemMenuBar(this);

    public void Enable() {
        this.enable();
    }

    private String Command;
    private float ResalePrice;
    Item drugsItem = new Item();

    /**
     * Set Item Name And Set Resale Price and Enable this Form
     *
     * @param Text
     * @param price
     */
    public void SetItem(String Text, float price) {
        txtItemName.setText(Text);
        txtResalePrice.setText(price + "");
        this.ResalePrice = price;
        this.enable();
        txtItemBarcode.setText(null);
        txtItemBatchNo.requestFocus();
    }

    public void Set(String Text) {
        Command = Text;
        butAdd.setText(Text);
    }

    /**
     * *
     * Save Stock
     */
    private void Add() {
        String Message = "";
        int value = MessageManager.YesOrNoMessage(null, null);

        //Set Stock Data
        Stock stock = new Stock();
        stock.setItemName(txtItemName.getText().trim());
        stock.setResalePrice(ResalePrice);
        try {
            stock.setQuantity(Integer.parseInt(txtQuantity.getText().trim()));
        } catch (NumberFormatException ex) {
            Message = "Invalid Quantity";
        }

        // Set Stock Batch Data
        StockBatch stockBatch = new StockBatch();
        stockBatch.setItemName(txtItemName.getText().trim());
        stockBatch.setBatch(txtItemBatchNo.getText().trim());
        try {
            stockBatch.setEXPDate(txtExpDate.getText().trim());
        } catch (NumberFormatException ex) {
            Message = "Invalid Exp Date";
        }

        try {
            stockBatch.setCostPrice(Float.parseFloat(txtCostPrice.getText().trim()));
        } catch (NumberFormatException ex) {
            Message = "Invalid Cost Price";
        }

        try {
            stockBatch.setQuantity(Integer.parseInt(txtQuantity.getText().trim()));
        } catch (NumberFormatException ex) {
            Message = "Invalid Quantity";
        }

        //Check Message
        if (value == 0) {

            try {
                // Meneger to Parse Data
                StockManager.SaveorUpdate(stock, stockBatch);
                Cancel();
            } catch (nullCreateUserException ex) {
                Message = "Invalid Create User";
            } catch (nullCreateDateException ex) {
                Message = "Invalid Create Date";
            } catch (nullCreateTimeException ex) {
                Message = "Invalid  Create Time";
            } catch (nullItemNameException ex) {
                Message = "Invalid  Item Name";
            } catch (nullBatchNoException ex) {
                Message = "Invalid Item Batch No";
            } catch (nullCostPriceException ex) {
                Message = "Invalid Cost Price";
            } catch (nullExpDateException ex) {
                Message = "Invalid  Exp Date";
            } catch (nullQuantityException ex) {
                Message = "Invalid Quantity";
            } catch (DatabaseException ex) {
                Message = "Database Error";
            } catch (nullResalpriceException ex) {
                Message = "Invalid Resale Price";
            }
        }
        lblMassage.setText(Message);
    }

    private void Cancel() {
        lblMassage.setText(null);
        txtItemBarcode.setText(null);
        txtItemName.setText(null);
        txtResalePrice.setText(null);
        txtItemBatchNo.setText(null);
        txtCostPrice.setText(null);
        txtExpDate.setText(null);
        txtQuantity.setText(null);

        txtItemBarcode.requestFocus();
    }

    private void jPanel1ComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jPanel1ComponentResized


    }//GEN-LAST:event_jPanel1ComponentResized

    private void butAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butAddActionPerformed
        Add();
    }//GEN-LAST:event_butAddActionPerformed

    private void txtExpDateKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExpDateKeyTyped
        if (txtExpDate.getText().length() == 10) {
            evt.consume();
        }
    }//GEN-LAST:event_txtExpDateKeyTyped

    private void butCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butCancelActionPerformed
        Cancel();

    }//GEN-LAST:event_butCancelActionPerformed

    private void MenuUserAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUserAddActionPerformed
        MenuBar.ShowUserAdding();
    }//GEN-LAST:event_MenuUserAddActionPerformed

    private void MenuUserUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUserUpdateActionPerformed
        MenuBar.ShowUserUpdate();
    }//GEN-LAST:event_MenuUserUpdateActionPerformed

    private void MenuUserDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUserDeleteActionPerformed
        MenuBar.ShowUserDelete();
    }//GEN-LAST:event_MenuUserDeleteActionPerformed

    private void MenuAdingDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAdingDrugsActionPerformed
        MenuBar.ShowAddingDrugs();
    }//GEN-LAST:event_MenuAdingDrugsActionPerformed

    private void MenuAddingDrugsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAddingDrugsItemActionPerformed
        MenuBar.ShowAddingDrugsItem();
    }//GEN-LAST:event_MenuAddingDrugsItemActionPerformed

    private void MenuAddingStockDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAddingStockDrugsActionPerformed
        MenuBar.ShowAddingStockDrugs();
    }//GEN-LAST:event_MenuAddingStockDrugsActionPerformed

    private void MenuUpdateDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUpdateDrugsActionPerformed
        MenuBar.ShowUpdateDrugs();
    }//GEN-LAST:event_MenuUpdateDrugsActionPerformed

    private void MenuUpdateDrugsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUpdateDrugsItemActionPerformed
        MenuBar.ShowUpdateDrugsItem();
    }//GEN-LAST:event_MenuUpdateDrugsItemActionPerformed

    private void MenuUpdateStockDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUpdateStockDrugsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuUpdateStockDrugsActionPerformed

    private void MenuDeleteStockDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDeleteStockDrugsActionPerformed
        MenuBar.ShowUpdateStockDrugs();
    }//GEN-LAST:event_MenuDeleteStockDrugsActionPerformed

    private void MenuLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLogOutMouseClicked
        MenuBar.LogOut();
    }//GEN-LAST:event_MenuLogOutMouseClicked

    private void MenuLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuLogOutActionPerformed

    private void txtItemBarcodeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemBarcodeKeyPressed
        BarcordEnter(evt.getKeyCode());
    }//GEN-LAST:event_txtItemBarcodeKeyPressed

    private void txtItemNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemNameKeyPressed
        GUIPopupTable Table = new GUIPopupTable();
        Table.Show("Stock", this);
        this.disable();
    }//GEN-LAST:event_txtItemNameKeyPressed

    private void txtResalePriceKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtResalePriceKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtResalePriceKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIAddStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIAddStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIAddStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIAddStock.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIAddStock().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAddingDrugsItem;
    private javax.swing.JMenuItem MenuAddingStockDrugs;
    private javax.swing.JMenuItem MenuAdingDrugs;
    private javax.swing.JMenuItem MenuDeleteDrugs;
    private javax.swing.JMenuItem MenuDeleteItemDrugs;
    private javax.swing.JMenuItem MenuDeleteStockDrugs;
    private javax.swing.JMenu MenuLogOut;
    private javax.swing.JMenuItem MenuUpdateDrugs;
    private javax.swing.JMenuItem MenuUpdateDrugsItem;
    private javax.swing.JMenuItem MenuUpdateStockDrugs;
    private javax.swing.JMenu MenuUpdateUser;
    private javax.swing.JMenuItem MenuUserAdd;
    private javax.swing.JMenuItem MenuUserDelete;
    private javax.swing.JMenuItem MenuUserUpdate;
    private javax.swing.JButton butAdd;
    private javax.swing.JButton butCancel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JLayeredPane jLayeredPane2;
    private javax.swing.JLayeredPane jLayeredPane3;
    private javax.swing.JLayeredPane jLayeredPane4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblMassage;
    private javax.swing.JFormattedTextField txtCostPrice;
    private javax.swing.JFormattedTextField txtExpDate;
    private javax.swing.JTextField txtItemBarcode;
    private javax.swing.JTextField txtItemBatchNo;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JFormattedTextField txtQuantity;
    private javax.swing.JTextField txtResalePrice;
    // End of variables declaration//GEN-END:variables

}
