/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import Bean.User;
import Logic.SystemLogOut;
import Logic.SystemMenuBar;
import Manager.GenericTypeManager;
import newException.DatabaseException;

/**
 *
 * @author PCPAL
 */
public class GUIHome extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public GUIHome() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuUpdateUser = new javax.swing.JMenu();
        MenuUserAdd = new javax.swing.JMenuItem();
        MenuUserUpdate = new javax.swing.JMenuItem();
        MenuUserDelete = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        MenuAdingDrugs = new javax.swing.JMenuItem();
        MenuAddingDrugsItem = new javax.swing.JMenuItem();
        MenuAddingStockDrugs = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        MenuUpdateDrugs = new javax.swing.JMenuItem();
        MenuUpdateDrugsItem = new javax.swing.JMenuItem();
        MenuUpdateStockDrugs = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        MenuDeleteDrugs = new javax.swing.JMenuItem();
        MenuDeleteItemDrugs = new javax.swing.JMenuItem();
        MenuDeleteStockDrugs = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        MenuLogOut = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Pharmacy System");

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Kristen ITC", 1, 66)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Wellcome My System");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1066, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 481, Short.MAX_VALUE)
        );

        jMenu1.setText("System");

        MenuUpdateUser.setText("User");

        MenuUserAdd.setText("Add User");
        MenuUserAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUserAddActionPerformed(evt);
            }
        });
        MenuUpdateUser.add(MenuUserAdd);

        MenuUserUpdate.setText("Update User");
        MenuUserUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUserUpdateActionPerformed(evt);
            }
        });
        MenuUpdateUser.add(MenuUserUpdate);

        MenuUserDelete.setText("Delete User");
        MenuUserDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUserDeleteActionPerformed(evt);
            }
        });
        MenuUpdateUser.add(MenuUserDelete);

        jMenu1.add(MenuUpdateUser);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");

        jMenu3.setText("Adding");

        MenuAdingDrugs.setText("Drugs");
        MenuAdingDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAdingDrugsActionPerformed(evt);
            }
        });
        jMenu3.add(MenuAdingDrugs);

        MenuAddingDrugsItem.setText("Drugs Item");
        MenuAddingDrugsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAddingDrugsItemActionPerformed(evt);
            }
        });
        jMenu3.add(MenuAddingDrugsItem);

        MenuAddingStockDrugs.setText("Drugs Stock");
        MenuAddingStockDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuAddingStockDrugsActionPerformed(evt);
            }
        });
        jMenu3.add(MenuAddingStockDrugs);

        jMenu2.add(jMenu3);

        jMenu4.setText("Update");

        MenuUpdateDrugs.setText("Drugs");
        MenuUpdateDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUpdateDrugsActionPerformed(evt);
            }
        });
        jMenu4.add(MenuUpdateDrugs);

        MenuUpdateDrugsItem.setText("Drugs Item");
        MenuUpdateDrugsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUpdateDrugsItemActionPerformed(evt);
            }
        });
        jMenu4.add(MenuUpdateDrugsItem);

        MenuUpdateStockDrugs.setText("Drugs Stock");
        MenuUpdateStockDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuUpdateStockDrugsActionPerformed(evt);
            }
        });
        jMenu4.add(MenuUpdateStockDrugs);

        jMenu2.add(jMenu4);

        jMenu5.setText("Delete");

        MenuDeleteDrugs.setText("Drugs");
        jMenu5.add(MenuDeleteDrugs);

        MenuDeleteItemDrugs.setText("Drugs Item");
        jMenu5.add(MenuDeleteItemDrugs);

        MenuDeleteStockDrugs.setText("Drugs Stock");
        MenuDeleteStockDrugs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuDeleteStockDrugsActionPerformed(evt);
            }
        });
        jMenu5.add(MenuDeleteStockDrugs);

        jMenu2.add(jMenu5);

        jMenuBar1.add(jMenu2);

        jMenu6.setText("Home");
        jMenuBar1.add(jMenu6);

        MenuLogOut.setText("LogOut");
        MenuLogOut.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuLogOutMouseClicked(evt);
            }
        });
        MenuLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuLogOutActionPerformed(evt);
            }
        });
        jMenuBar1.add(MenuLogOut);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    User user = new User();
    private final SystemMenuBar MenuBar = new SystemMenuBar(this);

    private void SetItemType() {

    }

    private void MenuLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuLogOutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuLogOutActionPerformed

    private void MenuLogOutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuLogOutMouseClicked
        MenuBar.LogOut();
    }//GEN-LAST:event_MenuLogOutMouseClicked

    private void MenuAdingDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAdingDrugsActionPerformed
        MenuBar.ShowAddingDrugs();
    }//GEN-LAST:event_MenuAdingDrugsActionPerformed

    private void MenuAddingDrugsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAddingDrugsItemActionPerformed
        MenuBar.ShowAddingDrugsItem();
    }//GEN-LAST:event_MenuAddingDrugsItemActionPerformed

    private void MenuUserAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUserAddActionPerformed
        MenuBar.ShowUserAdding();
    }//GEN-LAST:event_MenuUserAddActionPerformed

    private void MenuUserUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUserUpdateActionPerformed
        MenuBar.ShowUserUpdate();
    }//GEN-LAST:event_MenuUserUpdateActionPerformed

    private void MenuUserDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUserDeleteActionPerformed
        MenuBar.ShowUserDelete();
    }//GEN-LAST:event_MenuUserDeleteActionPerformed

    private void MenuUpdateDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUpdateDrugsActionPerformed
        MenuBar.ShowUpdateDrugs();
    }//GEN-LAST:event_MenuUpdateDrugsActionPerformed

    private void MenuUpdateDrugsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUpdateDrugsItemActionPerformed
        MenuBar.ShowUpdateDrugsItem();
    }//GEN-LAST:event_MenuUpdateDrugsItemActionPerformed

    private void MenuDeleteStockDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuDeleteStockDrugsActionPerformed
        MenuBar.ShowUpdateStockDrugs();
    }//GEN-LAST:event_MenuDeleteStockDrugsActionPerformed

    private void MenuUpdateStockDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuUpdateStockDrugsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MenuUpdateStockDrugsActionPerformed

    private void MenuAddingStockDrugsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuAddingStockDrugsActionPerformed
        MenuBar.ShowAddingStockDrugs();
    }//GEN-LAST:event_MenuAddingStockDrugsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUIHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem MenuAddingDrugsItem;
    private javax.swing.JMenuItem MenuAddingStockDrugs;
    private javax.swing.JMenuItem MenuAdingDrugs;
    private javax.swing.JMenuItem MenuDeleteDrugs;
    private javax.swing.JMenuItem MenuDeleteItemDrugs;
    private javax.swing.JMenuItem MenuDeleteStockDrugs;
    private javax.swing.JMenu MenuLogOut;
    private javax.swing.JMenuItem MenuUpdateDrugs;
    private javax.swing.JMenuItem MenuUpdateDrugsItem;
    private javax.swing.JMenuItem MenuUpdateStockDrugs;
    private javax.swing.JMenu MenuUpdateUser;
    private javax.swing.JMenuItem MenuUserAdd;
    private javax.swing.JMenuItem MenuUserDelete;
    private javax.swing.JMenuItem MenuUserUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
